[options]
admin_pass = admin
db_host = myDB19_test
db_user = chrizzzadmin
db_password = 051002
db_port = 5432
addons_path = addons_path = /mnt/extra-addons,/mnt/extra-addons/report-print-send
data_dir = /var/lib/odoo
